services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=SnackTechDb;User=sa;Password=teste@123;TrustServerCertificate=True;
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "teste@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
